### ISSUE TITLE
Erro na instalação no .NETFramework 4.6 ou superior

### ISSUE THREAD

**Issue by Deizo** [guibranco/ViaCEP#32]
Tentei realizar a instalação do pacote utilizando a linguagem C#, no Visual Studio 2019 e .NETFramework 4.6 e 4.7.2, porém é exibido o seguinte erro:

> Não foi possível instalar o pacote 'ViaCep 3.0.40'. Você está tentando instalar este pacote em um projeto que se destina a '.NETFramework,Version=v4.7.2', mas o pacote não contém nenhuma referência de assembly ou arquivo de conteúdo que seja compatível com essa estrutura. Para obter mais informações, entre em contato com o autor do pacote.				

A instalação no .NetCore funcionou normalmente.

Pelo readme, não localizei nenhuma menção sobre a versão para utilização.

**Comment by guibranco** [comment]
Vou verificar!

**Comment by guibranco** [comment]
@Deizo boa noite, pode tentar com a nova versão por favor ? 

```shell
Install-Package ViaCEP -Version 3.1.5

**Comment by Deizo** [comment]
@guibranco , boa noite! Agora está funcionando. Muito obrigado pelo rápido retorno!
