### ISSUE TITLE
Add Integration Tests

### ISSUE THREAD

**Issue by guibranco** [guibranco/ViaCEP#71]
Add integration tests

**Comment by Riju-bak** [comment]
Hi @guibranco, is this super urgent? If not, can I take it up?

**Comment by guibranco** [comment]
@Riju-bak yes, sure!

**Comment by Riju-bak** [comment]
@guibranco  So I was thinking about how to organize the integration tests, and the following options come into mind - 

1.  Create a separate project called `ViaCep.IntegrationTests` for the integration tests.
2. Write all the integration tests within one file called `IntegrationTests.cs` inside the `ViaCep.Tests` project
3. Write the integration tests inside `ViaCep.Tests` project itself but have separate test-files with names such as `AddressIntegrationTests.cs` and `ZipCodeIntegrationTests.cs` to make the type of the tests clear.

Which one do you think I must go for? If neither, then maybe you could tell me how you'd like to have them organizes

**Comment by guibranco** [comment]
I prefer the first one, a separate project, so it`s possible to run it or not easily.

**Comment by guibranco** [comment]
@Riju-bak merged! 
Nice job. Thanks for the effort!

**Comment by Riju-bak** [comment]
@guibranco You're welcome :)
